name: plt_poc
version: '1.0.0'
config-version: 2
profile: plt_poc

model-paths: ["models"]
macro-paths: ["macros"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  plt_sources:
    - { schema: 'K1_STAGING', label: 'k1' }
    - { schema: 'K1_PRIME_STAGING', label: 'k1_prime' }
  plt_database: "{{ env_var('SNOWFLAKE_DATABASE', 'PLT_POC') }}"
  plt_table: 'ORDERS'

models:
  plt_poc:
    plt:
      +materialized: incremental
    plt_sync:
      +materialized: incremental
