name: plt_poc
version: '1.0.0'
config-version: 2
profile: plt_poc

model-paths: ["models"]
macro-paths: ["macros"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  plt_poc:
    plt:
      +materialized: incremental
    plt_sync:
      +materialized: incremental
